// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddTodo(arg1:string,arg2:string,arg3:number):Promise<void>;

export function CheckDocking():Promise<string>;

export function DeleteTodo(arg1:string):Promise<void>;

export function Dock(arg1:string):Promise<void>;

export function FullQuit():Promise<void>;

export function GetConfig():Promise<models.AppConfig>;

export function GetImageBase64(arg1:string):Promise<string>;

export function GetMode():Promise<string>;

export function GetTodos():Promise<Array<models.TodoItem>>;

export function OpenMain():Promise<void>;

export function SelectFile():Promise<string>;

export function SetBallMenuState(arg1:boolean):Promise<void>;

export function SetWindowPosition(arg1:number,arg2:number):Promise<void>;

export function SetWindowSize(arg1:number,arg2:number):Promise<void>;

export function ToggleTodo(arg1:string):Promise<void>;

export function Undock(arg1:string):Promise<void>;

export function UpdateConfig(arg1:models.AppConfig):Promise<void>;
