// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTodo(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddTodo'](arg1, arg2, arg3);
}

export function CheckDocking() {
  return window['go']['main']['App']['CheckDocking']();
}

export function DeleteTodo(arg1) {
  return window['go']['main']['App']['DeleteTodo'](arg1);
}

export function Dock(arg1) {
  return window['go']['main']['App']['Dock'](arg1);
}

export function FullQuit() {
  return window['go']['main']['App']['FullQuit']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetImageBase64(arg1) {
  return window['go']['main']['App']['GetImageBase64'](arg1);
}

export function GetMode() {
  return window['go']['main']['App']['GetMode']();
}

export function GetTodos() {
  return window['go']['main']['App']['GetTodos']();
}

export function OpenMain() {
  return window['go']['main']['App']['OpenMain']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SetBallMenuState(arg1) {
  return window['go']['main']['App']['SetBallMenuState'](arg1);
}

export function SetWindowPosition(arg1, arg2) {
  return window['go']['main']['App']['SetWindowPosition'](arg1, arg2);
}

export function SetWindowSize(arg1, arg2) {
  return window['go']['main']['App']['SetWindowSize'](arg1, arg2);
}

export function ToggleTodo(arg1) {
  return window['go']['main']['App']['ToggleTodo'](arg1);
}

export function Undock(arg1) {
  return window['go']['main']['App']['Undock'](arg1);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}
